### ISSUE TITLE
ACPI aml and Bluetooth receiver

### ISSUE THREAD

**Issue by lazosweb** [vulgo/prime-b460i-plus-hackintosh#15]
@vulgo 
Regarding the ACPI aml files I had a "stupid" idea yesterday to copy your ACPI aml files from the repo in my EFI which made the hackintosh unbootable. I had to create another bootable USB stick to go into recovery mode, mount the EFI and restore the old aml files from a backup that I had.

The question. The repo's AML files are not for this board? I cannot use them?
I only have SSDT-AWAC.aml, SSDT-EC.aml, SSDT-PLUG.aml and SSDT-USBX.aml... you have more...

Regarding bluetooth. I have an ASUS USB-BT400. I think now in Monterey I have also the BlueTool.kext...
Anyway, if I have my bluetooth sony wh-1000xm3 connected to it and I am just like 30cm away from the dongle, if I turn my head the signal it's lost and the music shutters due to poor signal.

The question. Is this just a bad/unsupported bluetooth dongle or something that has to do with the USBs. I ordered a new m.2 card which has both Wireless and BT hopefully it will help.

Any feedback from your experience is appreciated... :)

**Comment by vulgo** [comment]
## ACPI Files in this repository

### SSDT-AC-WIRELESS-INTEL

Maybe useful for Windows or Linux users with certain Intel wireless cards. Maybe useful for macOS users using Intel wireless cards. I have no idea. I removed a lot of code from stock table xh_cmvd4 so this is an option to restore possible lost driver functionality for cards listed at the bottom of /README/README-SSDT-xh_cmvd4.md. I have no idea if it does anything useful as I don't have one of these cards. I know it does nothing if you don't.

### SSDT-AWAC-DISABLE

This is the standard SSDT-AWAC but does nothing if method _SB._INI already exists, it lets all OS use RTC

### SSDT-AWAC-HPET-DISABLE

Same as above but stops using the High Precision Event Timer like Apple did around when Kaby Lake rolled out. Again does nothing if method _SB._INI already exists by prior SSDT creating one

### SSDT-PLUG

Standard SSDT-PLUG for enabling CPU power management incompatible with the SSDT method for providing CPUFriend data, i think it is originally by RehabMan

### SSDT-SBUS-MCHC

Standard SMBUSPCI loading, AppleSMBUSController loading and Memory Controller device creating SSDT maybe originally devised by MasterChief, OpenCore has it so here it is as well

### SSDT-SLTP

Sets an SLTP value when we go to sleep, it is from [here](https://pikeralpha.wordpress.com/2017/01/12/debugging-sleep-issues/) where there is more, maybe for laptops with S0 low power states. I once found it to resolve a sleep issue so since then always include it, as the blog post says it is read by various drivers and I prefer they read normal S3 sleep if that is the sleep state being entered. On the other hand it may do nothing.

### SSDT-USBX

This is documented at /README/README-usbtool.command.md in the spoiler

### SSDT-xh_cmvd4

This is documented in /README/README-SSDT-xh_cmvd4.md

## config.plist

Using only the following files

- SSDT-AWAC-DISABLE
- SSDT-PLUG
- SSDT-SLPT
- SSDT-USBX
- SSDT-xh_cmvd4

```
<dict>
	<key>ACPI</key>
	<dict>
		<key>Add</key>
		<array>
			<dict>
				<key>Comment</key>
				<string>Enable AppleRTC</string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>SSDT-AWAC-DISABLE.aml</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Enable X86PlatformPlugin</string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>SSDT-PLUG.aml</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Enable IOPMSystemSleepType property</string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>SSDT-SLTP.aml</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Enable AppleUSBHostResources power properties</string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>SSDT-USBX.aml</string>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Add patched xh_cmvd4</string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>SSDT-xh_cmvd4.aml</string>
			</dict>
		</array>
		<key>Delete</key>
		<array>
			<dict>
				<key>All</key>
				<false/>
				<key>Comment</key>
				<string>Delete OEM xh_cmvd4</string>
				<key>Enabled</key>
				<true/>
				<key>OemTableId</key>
				<data>eGhfY212ZDQ=</data>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data>U1NEVA==</data>
			</dict>
			<dict>
				<key>All</key>
				<false/>
				<key>Comment</key>
				<string>Delete unused OEM UsbCTabl</string>
				<key>Enabled</key>
				<true/>
				<key>OemTableId</key>
				<data>VXNiQ1RhYmw=</data>
				<key>TableLength</key>
				<integer>0</integer>
				<key>TableSignature</key>
				<data>U1NEVA==</data>
			</dict>
		</array>
		...
	</dict>
	...
</dict>

```

## Use a USB 2.0 port for your Bluetooth dongle

[USB 3.0 Radio Frequency Interference Impact on 2.4 GHz Wireless Devices](https://www.usb.org/sites/default/files/327216.pdf)

## Generate a valid USBPorts.kext

- As is 2 USB 3.0 ports will only work at 2.0 speed
- Use the provided usbtool.command specific to this board or follow some guide
- Just don't connect one of the motherboard IDC USB connectors depending on the connector types available on your enclosure
