### ISSUE TITLE
Monterey

### ISSUE THREAD

**Issue by lazosweb** [vulgo/prime-b460i-plus-hackintosh#8]
Hi @vulgo,

Just to let you know that I updated to Monterey without any issues.
Your monitor fix works fine with Monterey.

My ASUS BT400 needs the BluetoothFix.kext...on Big Sur it was working without anything.

Other than that I do not see any problems...

**Comment by vulgo** [comment]
Hello @lazosweb i'm glad os12 mostly works, the feedback is most helpful.

I've done a fair bit of amateur research into the HD630 2 monitor problem. Learned about WhateverGreen.kext, looked at the source code of various open source framebuffer drivers, studied disassembly of the CFL framebuffer etc.

It needs a full modeset but the driver tries to avoid these to minimise flicker. I think the "removing 32 bit color mode from preferences" hack might work because then it differs from the "get current mode" method of the driver. Then it sets the mode.
